### ISSUE TITLE
1.2 - Inactive icon

### ISSUE THREAD

**Issue by pixilus** [arnoappenzeller/PiPifier#14] opened 2016-10-18 10:50 UTC
When you watching something in PiP-window and then press icon that return PiP-window to a web page, Pipifier dock icon became inactive and it's impossible to get PiP-window again without web page reloading. It's 1.2 specific issue. Could you please provide 1.1 link, this bug drives me nuts. :(

**Comment by arnoappenzeller** [comment] 2016-10-18 11:22
Can you provide a link to the video where this happens. Can't reproduce it with 1.2

**Comment by pixilus** [comment] 2016-10-18 11:32
It's standard HTML5 player, 1.1 worked like a charm with it

http://seasonvar.ru/serial-56-Zvzdnij_Krejser_Galaktika-3-season.html

**Comment by arnoappenzeller** [comment] 2016-10-18 12:52
Can't reproduce it there. By dock icon do you mean the icon next to the address bar in Safari?

**Comment by pixilus** [comment] 2016-10-18 15:16
Sorry, I've meant Pipifier icon in Safari's toolbar :)

http://prntscr.com/cvuqjn - here's the screenshot

**Comment by kabiroberai** [comment] 2016-10-18 15:45
I think that this should be fixed in `[f2240d8](https://github.com/arnoappenzeller/PiPifier/commit/f2240d8b4df0dd0947b8283a8396e8fed6652831)`, but if it isn't @arnoappenzeller you should add a toggle for disabling toolbar button validation.

**Comment by arnoappenzeller** [comment] 2016-10-18 16:35
I already uploaded a new version including this fix to the AppStore. Should be out in the next few days. I also think this should fix the bug even if I wasn't able to reproduce it in the first place.

**Comment by pixilus** [comment] 2016-10-18 17:01
Thank you guys! You're awesome! How to get new version without waiting AppStore update? :)

**Comment by arnoappenzeller** [comment] 2016-10-19 06:59
It's already in the AppStore ;)

**Closed by arnoappenzeller** 2016-10-19 06:59 UTC

**Comment by pixilus** [comment] 2016-10-21 17:08
Sorry, me again.

Personally for me the bug with inactive icon is still here, use the latest version, 1.2.2

How to get 1.1? :)
